### PR TITLE
make the combine script

### PR DESCRIPTION
**Pull request by Amr-Nash**

### CODE REVIEW

**Comment by Amr-Nash** [comment]
documentation is still not accurate

**Comment by OmarIthawi** [comment]
Thanks @Amr-Nash please create the Makefile and re-open against https://github.com/openedx/openedx-app-android.

I'll review there with Brian.

**Review by OmarIthawi — CHANGES_REQUESTED** [review]
Thanks @Amr-Nash please create the Makefile and re-open against https://github.com/openedx/openedx-app-android.

I'll review there with Brian.

**Comment by OmarIthawi** [comment]
@Amr-Nash please close this pull request and use the https://github.com/openedx/openedx-app-android so Brian and others can review it.

**Comment by Amr-Nash** [comment]
@OmarIthawi I have already opened it https://github.com/openedx/openedx-app-android/pull/317

**Pull request closed without merging**
